# Generated by Django 3.2 on 2021-05-06 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='modeified_time',
        ),
        migrations.AddField(
            model_name='location',
            name='modified_time',
            field=models.DateTimeField(auto_now=True, verbose_name='modified time'),
        ),
    ]
