# Generated by Django 3.2 on 2021-05-05 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='created time')),
                ('modeified_time', models.DateTimeField(auto_now=True, verbose_name='modeified time')),
                ('file', models.FileField(upload_to='posts/Y-m/', verbose_name='file')),
            ],
            options={
                'verbose_name': 'media',
                'verbose_name_plural': 'media',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='created time')),
                ('modeified_time', models.DateTimeField(auto_now=True, verbose_name='modeified time')),
                ('caption', models.TextField(blank=True, verbose_name='caption')),
            ],
            options={
                'verbose_name': 'post',
                'verbose_name_plural': 'posts',
            },
        ),
        migrations.CreateModel(
            name='PostTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='created time')),
                ('modeified_time', models.DateTimeField(auto_now=True, verbose_name='modeified time')),
            ],
            options={
                'verbose_name': 'post_tag',
                'verbose_name_plural': 'post_tags',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='created time')),
                ('modeified_time', models.DateTimeField(auto_now=True, verbose_name='modeified time')),
                ('title', models.CharField(max_length=32, verbose_name='title')),
            ],
            options={
                'verbose_name': 'tag',
                'verbose_name_plural': 'tags',
            },
        ),
        migrations.CreateModel(
            name='UserTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='created time')),
                ('modeified_time', models.DateTimeField(auto_now=True, verbose_name='modeified time')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_tags', to='social.tag')),
            ],
            options={
                'verbose_name': 'user_tag',
                'verbose_name_plural': 'user_tags',
            },
        ),
    ]
