# Generated by Django 3.2 on 2021-05-06 16:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='modeified_time',
        ),
        migrations.RemoveField(
            model_name='post',
            name='modeified_time',
        ),
        migrations.RemoveField(
            model_name='posttag',
            name='modeified_time',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='modeified_time',
        ),
        migrations.RemoveField(
            model_name='usertag',
            name='modeified_time',
        ),
        migrations.AddField(
            model_name='media',
            name='modified_time',
            field=models.DateTimeField(auto_now=True, verbose_name='modified time'),
        ),
        migrations.AddField(
            model_name='post',
            name='modified_time',
            field=models.DateTimeField(auto_now=True, verbose_name='modified time'),
        ),
        migrations.AddField(
            model_name='posttag',
            name='modified_time',
            field=models.DateTimeField(auto_now=True, verbose_name='modified time'),
        ),
        migrations.AddField(
            model_name='tag',
            name='modified_time',
            field=models.DateTimeField(auto_now=True, verbose_name='modified time'),
        ),
        migrations.AddField(
            model_name='usertag',
            name='modified_time',
            field=models.DateTimeField(auto_now=True, verbose_name='modified time'),
        ),
        migrations.AlterField(
            model_name='media',
            name='file',
            field=models.FileField(upload_to='posts/Y-m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'mp4', 'flv', 'mkv'])], verbose_name='file'),
        ),
    ]
